# Generated by Django 4.1.3 on 2022-11-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Location Name", max_length=100)),
                (
                    "descriptions",
                    models.TextField(
                        default="This is the amazing place.", max_length=500
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
