# Generated by Django 4.1.3 on 2022-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_delete_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                ("q_id", models.IntegerField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=30)),
                ("q_name", models.CharField(max_length=30)),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Sources",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=30)),
                ("link", models.URLField()),
            ],
        ),
    ]
