# Generated by Django 4.1.3 on 2022-12-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_problem_q_id_alter_sources_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem", name="link", field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="q_name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
