# Generated by Django 4.2.5 on 2023-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_uploadeddoc_delete_uploadedpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddoc',
            old_name='doc',
            new_name='doc_file',
        ),
        migrations.RemoveField(
            model_name='uploadeddoc',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadeddoc',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
